# Generated by Django 3.2.16 on 2022-11-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='uuid4 name')),
                ('status', models.TextField(blank=True, null=True, verbose_name='run status')),
                ('done', models.IntegerField(blank=True, null=True, verbose_name='Job done count')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Job total count')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Workflow run start date')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Workflow run complete date')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='RunWorkflowMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Message Status')),
                ('run_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.runworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='RunWorkflowJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField(blank=True, null=True, verbose_name='Job ID')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Job Message')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job Name')),
                ('input', models.CharField(blank=True, max_length=500, null=True, verbose_name='Input File')),
                ('output', models.CharField(blank=True, max_length=500, null=True, verbose_name='Output File')),
                ('log', models.CharField(blank=True, max_length=500, null=True, verbose_name='Log File')),
                ('wildcards', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wild Cards')),
                ('is_checkpoint', models.BooleanField(blank=True, null=True, verbose_name='Check Point')),
                ('shell_command', models.CharField(blank=True, max_length=300, null=True, verbose_name='Shell Command')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Job run start date')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Job run complete date')),
                ('run_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.runworkflow')),
            ],
        ),
    ]
