# Generated by Django 3.2.16 on 2022-12-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_runworkflow_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunWorkflowFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Output File')),
                ('status', models.CharField(blank=True, choices=[('UPLOADED', 'UPLOADED'), ('COMPLETE', 'COMPLETE'), ('CANCELLED', 'CANCELLED')], default='UPLOADED', max_length=30, null=True, verbose_name='Status')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Folder S3 Uploaded Date')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Folder Workflow Completed Date')),
            ],
        ),
    ]
