# Generated by Django 3.2.16 on 2022-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_runworkflowfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runworkflowfolder',
            name='folder_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Output Folder'),
        ),
    ]
