# Generated by Django 3.2.16 on 2022-12-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_runworkflowfolder_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runworkflowfolder',
            name='s3_prefix',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='S3 Prefix for find workflow'),
        ),
    ]
