# Generated by Django 3.2.16 on 2022-12-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_workflow_uuid'),
        ('api', '0005_runworkflowfolder_s3_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runworkflowfolder',
            name='s3_prefix',
        ),
        migrations.AddField(
            model_name='runworkflowfolder',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workflow'),
        ),
    ]
