# Generated by Django 3.2.16 on 2022-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='runworkflowjob',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Job Message'),
        ),
    ]
