# Generated by Django 3.2.16 on 2022-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_runworkflowjob_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='runworkflowjob',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Snakemake TimeStamp'),
        ),
        migrations.AddField(
            model_name='runworkflowmessage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Snakemake TimeStamp'),
        ),
    ]
