# Generated by Django 3.2.16 on 2022-12-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dbtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBTest',
        ),
    ]
