# Generated by Django 3.2.16 on 2022-11-30 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.UUID('dd0c66e2-b0a8-44ad-873d-8bd69521b4c5'), editable=False, null=True, verbose_name='UUID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('command', models.TextField(verbose_name='Command')),
                ('data', main.models.JSONField(default='{}', verbose_name='Data')),
                ('dag', models.TextField(blank=True, null=True, verbose_name='DAG')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Output')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Name')),
                ('snakefile', models.TextField(max_length=250, verbose_name='SnakeFile')),
                ('snakemake_id', models.TextField(verbose_name='SnakeMake ID')),
                ('status', models.TextField(choices=[('RUNNING', 'RUNNING'), ('NOTRUNNING', 'NOTRUNNING'), ('CANCELLED', 'CANCELLED')], default='NOTRUNNING', verbose_name='Status')),
                ('thread', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Thread ID')),
                ('retval', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Return Value')),
                ('workdir', models.TextField(max_length=250, verbose_name='Working Directory')),
                ('workflow_type', models.TextField(blank=True, choices=[('RNASEQ', 'RNASEQ'), ('ML', 'ML')], default='RNASEQ', null=True, verbose_name='Workflow Type')),
                ('git_address', models.TextField(blank=True, null=True, verbose_name='Source git address')),
                ('git_tag', models.TextField(blank=True, null=True, verbose_name='Source git tag')),
                ('git_branch', models.TextField(blank=True, null=True, verbose_name='Source git branch')),
                ('private', models.BooleanField(choices=[(False, 'Public (The workflow collection will be accessible by anyone)'), (True, 'Private (The workflow collection will be not listed.)')], default=False, verbose_name='Accessibility')),
                ('contributors', models.ManyToManyField(blank=True, help_text='users with edit permission to the workflow', related_name='workflow_contributors', related_query_name='contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributors')),
                ('owners', models.ManyToManyField(blank=True, default=None, related_name='workflow_owners', related_query_name='owners', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('msg', main.models.JSONField(default='{}')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workflow')),
            ],
        ),
    ]
