# Generated by Django 3.2.16 on 2022-12-05 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0402450a-5581-4868-ba7f-e5309ab14cb9'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
