# Generated by Django 3.2.16 on 2022-12-06 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e5f34bd9-a447-4195-bea7-364818a96d3b'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
