# Generated by Django 3.2.16 on 2022-12-09 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fb4f9d9b-6569-4cc0-b718-aeff6218da05'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
