# Generated by Django 3.2.16 on 2022-12-12 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('f38a1413-e5e9-4865-bee2-ea8819ee20c6'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
