# Generated by Django 3.2.16 on 2022-12-12 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='s3_prefix',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Unique S3 Prefix in Snakefile'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6c211317-a759-48b8-b5ae-b2570bf75015'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
