# Generated by Django 3.2.16 on 2022-12-12 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221212_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('b8e5e4fe-07f4-4755-8fb0-ed06b9fcaea6'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
