# Generated by Django 3.2.16 on 2022-12-12 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('edcffa06-80f5-4539-824b-82a0d026cd8f'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
