# Generated by Django 3.2.16 on 2022-12-27 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('797884ba-a1d3-4346-b023-a8b98a11e5ac'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
