# Generated by Django 3.2.16 on 2022-12-28 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('4dfed985-9ae0-42ce-bddb-4dd2d56c4d8e'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
