# Generated by Django 3.2.16 on 2022-12-30 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_workflow_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('40064445-0f8e-408e-aba0-ea2b4216ecf2'), editable=False, null=True, verbose_name='UUID'),
        ),
    ]
